name: "CI-CD"
on:
  push:
    branches:
      - main

jobs:
  Setup:
    name: CI/CD
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'

      - name: Install backend dependencies
        run: |
          echo "### Installing backend dependencies ###"
          bun i
        working-directory: backend
        
      - name: Build backend
        run: |
          echo "### Build backend ###"
          bun run build
        working-directory: backend

      - name: Restart backend
        run: |
          echo "### Restart backend ###"
          pm2 restart 0
        working-directory: backend

      - name: Wait for backend to be ready
        run: |
          echo "### Waiting for backend to be ready ###"
          while ! nc -z localhost 8000; do
            echo "Backend is not ready yet. Retrying in 5 seconds"
            sleep 5
          done

      - name: Install frontend dependencies
        run: |
          echo "### Installing frontend dependencies ###"
          bun i
        working-directory: frontend

      - name: Build frontend
        run: |
          echo "### Build frontend ###"
          bun run build
        working-directory: frontend

      - name: Restart frontend
        run: |
          echo "### Restart frontend ###"
          pm2 restart 1
        working-directory: frontend

      - name: Wait for frontend to be ready
        run: |
          echo "### Waiting for frontend to be ready ###"
          while ! nc -z localhost 3000; do
            echo "Frontend is not ready yet. Retrying in 5 seconds"
            sleep 5
          done

      - name: Finish
        run: |
          echo "Successful application build 🎉"